const hotels2 = [
  {
    title: "Sheraton Dublin Hotel",
    type: "hotel",
    description: "A luxurious hotel located in the heart of Dublin",
    city: "Dublin",
    address: "123 Main St",
    distance: "2 miles from city center",
    cheapestPrice: 150,
    photos: [
      {
        imageUrl: "https://example.com/photo.jpg",
        altText: "Sheraton Dublin Hotel",
      },
    ],
    rooms: ["Deluxe Room", "Executive Suite"],
    featured: true,
    rating: 4.5,
  },
  {
    title: "Villa Paradiso",
    type: "villa",
    description: "A beautiful villa with stunning views of the Mediterranean",
    city: "Dublin",
    address: "456 Ocean Ave",
    distance: "5 miles from city center",
    cheapestPrice: 300,
    photos: [
      { imageUrl: "https://example.com/photo.jpg", altText: "Villa Paradiso" },
    ],
    rooms: ["Master Suite", "Guest Room"],
    featured: false,
    rating: 4.8,
  },
  {
    title: "Grand Resort Austin",
    type: "resort",
    description: "A sprawling resort located in the Texas Hill Country",
    city: "Austin",
    address: "789 Resort Way",
    distance: "10 miles from downtown",
    cheapestPrice: 200,
    photos: [
      {
        imageUrl: "https://example.com/photo.jpg",
        altText: "Grand Resort Austin",
      },
    ],
    rooms: ["Bungalow", "Cabana"],
    featured: true,
    rating: 4.2,
  },
  {
    title: "The Londoner",
    type: "hotel",
    description: "A boutique hotel in the heart of London's West End",
    city: "London",
    address: "101 Piccadilly",
    distance: "1 mile from Buckingham Palace",
    cheapestPrice: 250,
    photos: [
      { imageUrl: "https://example.com/photo.jpg", altText: "The Londoner" },
    ],
    rooms: ["Luxury Suite", "Junior Suite"],
    featured: false,
    rating: 4.9,
  },
  {
    title: "Reno Ski Lodge",
    type: "hotel",
    description: "A cozy hotel at the base of the Sierra Nevada mountains",
    city: "Reno",
    address: "321 Ski Run Rd",
    distance: "5 miles from downtown",
    cheapestPrice: 100,
    photos: [
      { imageUrl: "https://example.com/photo.jpg", altText: "Reno Ski Lodge" },
    ],
    rooms: ["Standard Room", "Family Suite"],
    featured: true,
    rating: 4.1,
  },
  {
    title: "City View Apartment",
    type: "apartment",
    description: "A modern apartment with stunning views of downtown Austin",
    city: "Austin",
    address: "567 4th St",
    distance: "1 mile from 6th Street",
    cheapestPrice: 125,
    photos: [
      {
        imageUrl: "https://example.com/photo.jpg",
        altText: "City View Apartment",
      },
    ],
    rooms: ["Studio", "One Bedroom"],
    featured: false,
    rating: 4.3,
  },
  {
    title: "Luxury Villa London",
    type: "villa",
    description: "A luxurious villa with a private pool in the heart of London",
    city: "London",
    address: "12 Kensington Park Gardens",
    distance: "2 miles from Hyde Park",
    cheapestPrice: 500,
    photos: [
      {
        imageUrl: "https://example.com/photo.jpg",
        altText: "Luxury Villa London",
      },
    ],
    rooms: ["Master Suite", "Guest Room"],
    featured: true,
    rating: 4.7,
  },
  {
    title: "Austin Downtown Cabin",
    type: "cabin",
    description: "A cozy cabin in the heart of downtown Austin",
    city: "Austin",
    address: "789 Main St",
    distance: "0.5 miles from 6th Street",
    cheapestPrice: 75,
    photos: [
      {
        imageUrl: "https://example.com/photo.jpg",
        altText: "Austin Downtown Cabin",
      },
    ],
    rooms: ["Standard Cabin", "Deluxe Cabin"],
    featured: false,
    rating: 3.9,
  },
  {
    title: "Reno Resort and Casino",
    type: "resort",
    description: "A luxurious resort with a casino in the heart of Reno",
    city: "Reno",
    address: "456 Casino Dr",
    distance: "1 mile from downtown",
    cheapestPrice: 175,
    photos: [
      {
        imageUrl: "https://example.com/photo.jpg",
        altText: "Reno Resort and Casino",
      },
    ],
    rooms: ["Deluxe Room", "Executive Suite"],
    featured: true,
    rating: 4.4,
  },
  {
    title: "London Apartment with Terrace",
    type: "apartment",
    description:
      "A stylish apartment with a private terrace in the heart of London",
    city: "London",
    address: "789 Oxford St",
    distance: "2 miles from Buckingham Palace",
    cheapestPrice: 200,
    photos: [
      {
        imageUrl: "https://example.com/photo.jpg",
        altText: "London Apartment with Terrace",
      },
    ],
    rooms: ["One Bedroom", "Two Bedroom"],
    featured: false,
    rating: 4.6,
  },
];
